<!DOCTYPE html>
<html lang="en">
<head>
  
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    
    <link rel="shortcut icon" href="/img/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title>Cluster Serving - Analytics Zoo</title>
    <link href="/css/bootstrap-3.3.7.min.css" rel="stylesheet">
    <link href="/css/font-awesome-4.7.0.css" rel="stylesheet">
    <link href="/css/base.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/highlight.css">
    <link href="../../extra.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="/js/jquery-3.2.1.min.js"></script>
    <script src="/js/bootstrap-3.3.7.min.js"></script>
    <script src="/js/highlight.pack.js"></script>
    
    <base target="_top">
    <script>
      var base_url = '../..';
      var is_top_frame = false;
        
        var pageToc = [
          {title: "Programming Guide", url: "#programming-guide", children: [
              {title: "Quick Start", url: "#quick-start" },
              {title: "Workflow Overview", url: "#workflow-overview" },
              {title: "Deploy your Own Cluster Serving", url: "#deploy-your-own-cluster-serving" },
              {title: "Optional Operations", url: "#optional-operations" },
          ]},
        ];

    </script>
    <script src="/js/base.js"></script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-125166209-1', 'analytics-zoo.github.io');
        ga('send', 'pageview');
    </script> 
</head>

<body>
<script>
if (is_top_frame) { $('body').addClass('wm-top-page'); }
</script>



<div class="container-fluid wm-page-content">
    
    <h1><strong>Cluster Serving</strong></h1>
    <hr>
    <h1 id="programming-guide">Programming Guide</h1>
<p>Analytics Zoo Cluster Serving is a lightweight distributed, real-time serving solution that supports a wide range of deep learning models (such as TensorFlow, PyTorch, Caffe, BigDL and OpenVINO models). It provides a simple pub/sub API, so that the users can easily send their inference requests to the input queue (using a simple Python API); Cluster Serving will then automatically manage the scale-out and real-time model inference across a large cluster (using distributed streaming frameworks such as Apache Spark Streaming, Apache Flink, etc.) </p>
<p>The overall architecture of Analytics Zoo Cluster Serving solution is illustrated as below: </p>
<p><img alt="overview" src="../cluster_serving_overview.jpg" /></p>
<p>Note: currently only <strong>image classification</strong> models are supported.</p>
<p>This page contains the guide for you to run Analytics Zoo Cluster Serving, including following:</p>
<ul>
<li>
<p><a href="#Quick-Start">Quick Start</a></p>
</li>
<li>
<p><a href="#Workflow-Overview">Workflow Overview</a> </p>
</li>
<li>
<p><a href="#Deploy-Your-Own-Cluster-Serving">Deploy Your Own Cluster Serving</a></p>
</li>
<li>
<p><a href="#1-Installation">Installation</a></p>
</li>
<li>
<p><a href="#2-Configuration">Configuration</a> </p>
</li>
<li>
<p><a href="#3-Launching-Service">Launching Service</a></p>
</li>
<li>
<p><a href="#4-Model-inference">Model inference</a></p>
</li>
<li>
<p><a href="#Optional-Operations">Optional Operations</a></p>
<ul>
<li>
<p><a href="#Update-Model-or-Configurations">Update Model or Configurations</a></p>
</li>
<li>
<p><a href="#Logs-and-Visualization">Logs and Visualization</a></p>
</li>
</ul>
</li>
</ul>
<h2 id="quick-start">Quick Start</h2>
<p>This section provides a quick start example for you to run Analytics Zoo Cluster Serving. To simplify the example, we use docker to run Cluster Serving. If you do not have docker installed, <a href="https://docs.docker.com/install/">install docker</a> first. The quick start example contains all the necessary components so the first time users can get it up and running within minutes:</p>
<ul>
<li>A docker image for Analytics Zoo Cluster Serving (with all dependencies installed)</li>
<li>A sample configuration file</li>
<li>A sample trained TensorFlow model, and sample data for inference</li>
<li>A sample Python client program</li>
</ul>
<p>Use one command to run Cluster Serving container.</p>
<pre><code>docker run -itd --name cluster-serving --net=host intelanalytics/zoo-cluster-serving:0.7.0
</code></pre>

<p>Log into the container using <code>docker exec -it cluster-serving bash</code>. </p>
<p>We already prepared <code>analytics-zoo</code> and <code>opencv-python</code> with pip in this container. And prepared model in <code>model</code> directory with following structure.</p>
<pre><code>cluster-serving | 
               -- | model
                 -- frozen_graph.pb
                 -- graph_meta.json
</code></pre>

<p>Start Cluster Serving using <code>cluster-serving-start</code>. </p>
<p>Run python program <code>python quick_start.py</code> to push data into queue and get inference result. </p>
<p>Then you can see the inference output in console. </p>
<pre><code>image: fish1.jpeg, classification-result: class: 1's prob: 0.9974158
image: cat1.jpeg, classification-result: class: 287's prob: 0.52377725
image: dog1.jpeg, classification-result: class: 207's prob: 0.9226527
</code></pre>

<p>Wow! You made it!</p>
<p>Note that the Cluster Serving quick start example will run on your local node only. Check the <a href="#Deploy-Your-Own-Cluster-Serving">Deploy Your Own Cluster Serving</a> section for how to configure and run Cluster Serving in a distributed fashion.</p>
<p>For more details, you could also see the log and performance by go to <code>localhost:6006</code> in your browser and refer to <a href="#Logs-and-Visualization">Logs and Visualization</a>, or view the source code of <code>quick_start.py</code> <a href="https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/serving/quick_start.py">here</a>, or refer to <a href="../APIGuide/">API Guide</a>.</p>
<h2 id="workflow-overview">Workflow Overview</h2>
<p>The figure below illustrates the simple 3-step "Prepare-Launch-Inference" workflow for Cluster Serving.</p>
<p><img alt="steps" src="../cluster_serving_steps.jpg" /></p>
<h4 id="1-install-and-prepare-cluster-serving-environment-on-a-local-node">1. Install and prepare Cluster Serving environment on a local node:</h4>
<ul>
<li>Copy a previously trained model to the local node; currently TensorFlow, PyTorch, Caffe, BigDL and OpenVINO models are supported.</li>
<li>Install Analytics Zoo on the local node (e.g., using a single pip install command)</li>
<li>Configure Cluster Server on the local node, including the file path to the trained model and the address of the cluster (such as Apache Hadoop YARN cluster, Spark Cluster, K8s cluster, etc.).
Please note that you only need to deploy the Cluster Serving solution on a single local node, and NO modifications are needed for the (YARN or K8s) cluster. </li>
</ul>
<h4 id="2-launch-the-cluster-serving-service">2. Launch the Cluster Serving service</h4>
<p>You can launch the Cluster Serving service by running the startup script on the local node. Under the hood, Cluster Serving will automatically deploy the trained model and serve the model inference requests across the cluster in a distributed fashion. You may monitor its runtime status (such as inference throughput) using TensorBoard. </p>
<h4 id="3-distributed-real-time-streaming-inference">3. Distributed, real-time (streaming) inference</h4>
<p>Cluster Serving provides a simple pub/sub API to the users, so that you can easily send the inference requests to an input queue (currently Redis Streams is used) using a simple Python API.</p>
<p>Cluster Serving will then read the requests from the Redis stream, run the distributed real-time inference across the cluster (using Spark Streaming or Flink), and return the results back through Redis. As a result, you may get the inference results again using a simple Python API.</p>
<h2 id="deploy-your-own-cluster-serving">Deploy your Own Cluster Serving</h2>
<h3 id="1-installation">1. Installation</h3>
<p>It is recommended to install Cluster Serving by pulling the pre-built Docker image to your local node, which have packaged all the required dependencies. Alternatively, you may also manually install Cluster Serving (through either pip or direct downloading) as well as Spark, Redis and TensorBoard (for visualizing the serving status) on the local node.</p>
<h4 id="docker">Docker</h4>
<pre><code>docker pull intelanalytics/zoo-cluster-serving
</code></pre>

<p>then, (or directly run <code>docker run</code>, it will pull the image if it does not exist)</p>
<pre><code>docker run --name cluster-serving --net=host -itd intelanalytics/zoo-cluster-serving:0.7.0 bash
</code></pre>

<p>Log into the container</p>
<pre><code>docker exec -it cluster-serving bash
</code></pre>

<p><code>cd ./cluster-serving</code>, you can see all the environments are prepared.</p>
<h5 id="yarn-user">Yarn user</h5>
<p>For Yarn user using docker, you have to set additional config, thus you need to call following when starting the container</p>
<pre><code>docker run --name cluster-serving --net=host -v /path/to/HADOOP_CONF_DIR:/opt/work/HADOOP_CONF_DIR -e HADOOP_CONF_DIR=/opt/work/HADOOP_CONF_DIR -itd intelanalytics/zoo-cluster-serving:0.7.0 bash
</code></pre>

<h4 id="manual-installation">Manual installation</h4>
<p>Non-Docker users need to install <a href="https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz">Spark 2.4.3</a>, <a href="https://redis.io/topics/quickstart">Redis</a> and <a href="https://www.tensorflow.org/tensorboard/get_started">TensorBoard</a>.</p>
<p>After preparing dependencies above, make sure the environment variable <code>$SPARK_HOME</code> (/path/to/spark-SPARK_VERSION-bin-hadoop-HADOOP_VERSION), <code>$REDIS_HOME</code>(/path/to/redis-REDIS_VERSION) is set before following steps. </p>
<p>Cluster Sering use TensorBoard to visualize the serving status. Use <code>pip install tensorboard</code> to install TensorBoard.</p>
<p>Install Analytics Zoo by Download Release or Pip.</p>
<h5 id="download-release">Download Release</h5>
<p>Download Analytics Zoo from <a href="https://analytics-zoo.github.io/master/#release-download/">release page</a> on the local node. </p>
<p>Unzip the file and go into directory <code>analytics-zoo</code>, run <code>export ANALYTICS_ZOO_HOME=$(pwd)</code> to set <code>$ANALYTICS_ZOO_HOME</code> variable.</p>
<p>Run <code>source analytics-zoo/bin/analytics-zoo-env.sh</code> to set environment.</p>
<p>Go to <code>analytics-zoo/scripts/cluster-serving</code>, run <code>cluster-serving-init</code>.</p>
<p>Run <code>export OMP_NUM_THREADS=all</code> if you want to use all cores on your machine to do inference in parallel manner.</p>
<h5 id="pip">Pip</h5>
<p><code>pip install analytics-zoo</code>. And go to any directory, run <code>cluster-serving-init</code>.</p>
<p>Run <code>export OMP_NUM_THREADS=all</code> if you want to use all cores on your machine to do inference in parallel manner.</p>
<h3 id="2-configuration">2. Configuration</h3>
<h4 id="how-to-config">How to Config</h4>
<p>After <a href="#1-Installation">Installation</a>, you will see a config file <code>config.yaml</code> in your current working directory. This file contains all the configurations that you can customize for your Cluster Serving. See an example of <code>config.yaml</code> below.</p>
<pre><code>## Analytics Zoo Cluster Serving Config Example

model:
  # model path must be set
  path: /opt/work/model
data:
  # default, localhost:6379
  src:
  # default, 3,224,224
  image_shape:
params:
  # default, 4
  batch_size:
  # default, 1
  top_n:
spark:
  # default, local[*], change this to spark://, yarn, k8s:// etc if you want to run on cluster
  master: local[*]
  # default, 4g
  driver_memory:
  # default, 1g
  executor_memory:
  # default, 1
  num_executors:
  # default, 4
  executor_cores:
  # default, 4
  total_executor_cores:
</code></pre>

<h4 id="preparing-model">Preparing Model</h4>
<p>Currently Analytics Zoo Cluster Serving supports TensorFlow, Caffe, PyTorch, BigDL, OpenVINO models. Note that currently only <strong>image classification</strong> models are supported.</p>
<p>You need to put your model file into a directory and the directory could have layout like following according to model type, note that only one model is allowed in your directory.</p>
<p><strong>Tensorflow</strong></p>
<pre><code>|-- model
   |-- frozen_graph.pb
   |-- graph_meta.json
</code></pre>

<p><strong>Caffe</strong></p>
<pre><code>|-- model
   |-- xx.prototxt
   |-- xx.caffemodel
</code></pre>

<p><strong>Pytorch</strong></p>
<pre><code>|-- model
   |-- xx.pt
</code></pre>

<p><strong>BigDL</strong></p>
<pre><code>|--model
   |-- xx.model
</code></pre>

<p><strong>OpenVINO</strong></p>
<pre><code>|-- model
   |-- xx.xml
   |-- xx.bin
</code></pre>

<p>Put the model in any of your local directory, and set <code>model:/path/to/dir</code>.</p>
<h4 id="other-configuration">Other Configuration</h4>
<p>The field <code>input</code> contains your input data configuration.</p>
<ul>
<li>src: the queue you subscribe for your input data, e.g. a default config of Redis on local machine is <code>localhost:6379</code>. Note that please use the host address in your network instead of localhost or 127.0.0.1 when you run serving in cluster, and make sure other nodes in cluster could also recognize this address.</li>
<li>image_shape: the shape of your input data, e.g. a default config for pretrained imagenet is <code>3,224,224</code>. You should use the same shape of data which trained your model. In TensorFlow the format is usually HWC and in other models the format is usually CHW.</li>
</ul>
<p>The field <code>params</code> contains your inference parameter configuration.</p>
<ul>
<li>batch_size: the batch size you use for model inference. We recommend this value to be not smaller than 4 and not larger than 512. In general, using larger batch size means higher throughput, but also increase the latency between batches accordingly.</li>
<li>top_n: the top N classes in the prediction result. <strong>note:</strong> if the top-N number is larger than model output size of the the final layer, it would just return all the outputs.</li>
</ul>
<p>The field <code>spark</code> contains your spark configuration.</p>
<ul>
<li>master: Your cluster address, same as parameter <code>master</code> in spark</li>
<li>driver_memory: same as parameter <code>driver-memory</code> in spark</li>
<li>executor_memory: same as parameter <code>executor-memory</code> in spark</li>
<li>num_executors: same as parameter <code>num-executors</code> in spark</li>
<li>executor_cores: same as paramter <code>executor-cores</code> in spark</li>
<li>total_executor_cores: same as parameter <code>total-executor-cores</code> in spark</li>
</ul>
<p>For more details of these config, please refer to <a href="https://spark.apache.org/docs/latest/configuration.html">Spark Official Document</a></p>
<h3 id="3-launching-service">3. Launching Service</h3>
<p>We provide following scripts to start, stop, restart Cluster Serving. </p>
<h4 id="start">Start</h4>
<p>You can use following command to start Cluster Serving.</p>
<pre><code>cluster-serving-start
</code></pre>

<p>This command will start Redis and TensorBoard if they are not running. Note that you need to provide <code>REDIS_HOME</code> environment variable as mentioned in <a href="#1-Installation">Installation</a>.</p>
<h4 id="stop">Stop</h4>
<p>You can use following command to stop Cluster Serving. Data in Redis and TensorBoard service will persist.</p>
<pre><code>cluster-serving-stop
</code></pre>

<h4 id="restart">Restart</h4>
<p>You can use following command to restart Cluster Serving.</p>
<pre><code>cluster-serving-restart
</code></pre>

<h4 id="shut-down">Shut Down</h4>
<p>You can use following command to shutdown Cluster Serving. This operation will stop all running services related to Cluster Serving, specifically, Redis and TensorBoard. Note that your data in Redis will be removed when you shutdown. </p>
<pre><code>cluster-serving-shutdown
</code></pre>

<p>If you are using Docker, you could also run <code>docker rm</code> to shutdown Cluster Serving.</p>
<h3 id="4-model-inference">4. Model Inference</h3>
<p>We support Python API for conducting inference with Data Pipeline in Cluster Serving. The requirements of API are <code>opencv-python</code>, <code>pyyaml</code>, <code>redis</code>.</p>
<p>We provide basic usage here, for more details, please see <a href="../APIGuide/">API Guide</a>.</p>
<h4 id="input-and-output-api">Input and Output API</h4>
<p>To input data to queue, you need a <code>InputQueue</code> instance, and using <code>enqueue</code> method by giving an image path or image ndarray. See following example.</p>
<pre><code>from zoo.serving.client import InputQueue
input_api = InputQueue()
input_api.enqueue_image('my-image1', 'path/to/image1')

import cv2
image2 = cv2.imread('path/to/image2')
input_api.enqueue_image('my-image2', image2)
</code></pre>

<p>To get data from queue, you need a <code>OutputQueue</code> instance, and using <code>query</code> or <code>dequeue</code> method. The <code>query</code> method takes image uri as parameter and returns the corresponding result. The <code>dequeue</code> method takes no parameter and just returns all results and also delete them in data queue. See following example.</p>
<pre><code>from zoo.serving.client import OutputQueue
output_api = OutputQueue()
img1_result = output_api.query('img1')
all_result = output_api.dequeue() # the output queue is empty after this code
</code></pre>

<h4 id="output-format">Output Format</h4>
<p>Consider the code above, in <a href="#Input-and-Output-API">Input and Output API</a> Section.</p>
<pre><code>img1_result = output_api.query('img1')
</code></pre>

<p>The <code>img1_result</code> is a json format string, like following:</p>
<pre><code>'{&quot;class_1&quot;:&quot;prob_1&quot;,&quot;class_2&quot;:&quot;prob_2&quot;,...,&quot;class_n&quot;,&quot;prob_n&quot;}'
</code></pre>

<p>Where <code>n</code> is the number of <code>top_n</code> in your configuration file. This string could be parsed by <code>json.loads</code>.</p>
<pre><code>import json
result_class_prob_map = json.loads(img1_result)
</code></pre>

<h2 id="optional-operations">Optional Operations</h2>
<h3 id="update-model-or-configurations">Update Model or Configurations</h3>
<p>To update your model, you could replace your model file in your model directory, and restart Cluster Serving by <code>cluster-serving-restart</code>. Note that you could also change your configurations in <code>config.yaml</code> and restart serving.</p>
<h3 id="logs-and-visualization">Logs and Visualization</h3>
<h4 id="logs">Logs</h4>
<p>We use log to save Cluster Serving information and error. To see log, please refer to <code>cluster-serving.log</code>.</p>
<h4 id="visualization">Visualization</h4>
<p>TensorBoard is integrated into Cluster Serving. TensorBoard service is started with Cluster Serving. Once your serving starts, you can go to <code>localhost:6006</code> to see visualization of your serving.</p>
<p>Analytics Zoo Cluster Serving provides 2 attributes in Tensorboard so far, <code>Serving Throughput</code> and <code>Total Records Number</code>.</p>
<ul>
<li>
<p><code>Serving Throughput</code>: The overall throughput, including preprocessing and postprocessing of your serving. The line should be relatively stable after first few records. If this number has a drop and remains lower than previous, you might have lost the connection of some nodes in your cluster.</p>
</li>
<li>
<p><code>Total Records Number</code>: The total number of records that Cluster Serving gets so far.</p>
</li>
</ul>
<p>See example of visualization:</p>
<p><img alt="Example Chart" src="../example-chart.png" /></p>

  <br>
</div>

<footer class="col-md-12 wm-page-content">
  <p>Documentation built with <a href="http://www.mkdocs.org/">MkDocs</a> using <a href="https://github.com/gristlabs/mkdocs-windmill">Windmill</a> theme by Grist Labs.</p>
</footer>

</body>
</html>